spring.application.name=hackerton

spring.datasource.url=jdbc:mysql://localhost:3306/picknu?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

openai.api.key=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